apiVersion: apps/v1
kind: Deployment
metadata:
  name: corecrud-mongodb
  labels:
    app: corecrud-mongodb
spec:
  containers:
  - name: corecrud-container-mongodb
    image: mongo:4.1
    env:
    - name: MONGO_INITDB_ROOT_USERNAME
      value: "mongouser"
    - name: MONGO_INITDB_ROOT_PASSWORD
      value: "GPX4WOwpcvOc9Wm70gAG8It7tKA0Cy090ZVO82cEJsExogsMDY"
    ports:
    - containerPort: 27017

---

apiVersion: v1
kind: Service
metadata:
  name: corecrud-mongodb-service
spec:
  selector:
    app: corecrud-mongodb
  ports:
  - protocol: TCP
    port: 27017

---

apiVersion: apps/v1
kind: Pod
metadata:
  name: corecrud
      labels:
        app: corecrud
spec:      
  containers:
    - name: corecrud-container
      image: fabricioveronez/corecrud
      imagePullPolicy: Always
      ports:
        - containerPort: 80
      env:
        - name: MONGO_CONNECTIONSTRING
          value: "mongodb://mongouser:GPX4WOwpcvOc9Wm70gAG8It7tKA0Cy090ZVO82cEJsExogsMDY@corecrud-mongodb:27017/admin"
        - name: MONGO_DATABASE
          value: "admin"

---

kind: Service
apiVersion: v1
metadata:
  name: corecrud-service
spec:
  selector:
    app: corecrud
  ports:
  - protocol: TCP
    port: 80
  type: LoadBalancer