apiVersion: apps/v1
kind: Deployment
metadata:
  name: corecrud-mongodb
spec:  
  selector:
    matchLabels:
      app: corecrud-mongodb
  template:
    metadata:
      labels:
        app: corecrud-mongodb
    spec:
      containers:
      - name: corecrud-container-mongodb
        image: mongo:4.1
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "mongouser"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "GPX4WOwpcvOc9Wm70gAG8It7tKA0Cy090ZVO82cEJsExogsMDY"
        ports:
        - containerPort: 27017
