version: '3.4'

services:
  corecrud.api:
    image: fabricioveronez/corecrud
    ports:
      - "8181:80"
    build:
      context: .
      dockerfile: CoreCRUD/CoreCRUD.Api/Dockerfile
    networks:
      - corecrud
    environment: 
      MONGO_CONNECTIONSTRING: mongodb://mongouser:GPX4WOwpcvOc9Wm70gAG8It7tKA0Cy090ZVO82cEJsExogsMDY@corecrud-mongodb:27017/admin
      MONGO_DATABASE: admin

  corecrud-mongodb:
    image: mongo:4.1
    volumes:
      - db_mongo:/data/db
    networks:
      - corecrud
    restart: always
    command: --storageEngine wiredTiger
    environment: 
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: GPX4WOwpcvOc9Wm70gAG8It7tKA0Cy090ZVO82cEJsExogsMDY

volumes:
  db_mongo:
networks: 
  corecrud: 
    driver: bridge